Create zh_tw.json
CoFH/CoFHCore pull request #22
Opened 2022-11-26 10:15 UTC by Jimmy-sheep

Add Traditional Chinese Language, copy from zh_cn.json, but change about 5% of phraseology.

2022-11-26 21:04 UTC, StarskyXIII requested changes
簡轉繁已經夠輕鬆了，連開個遊戲檢查都不願意嗎

2022-11-26 21:04 UTC, StarskyXIII commented on src/main/resources/assets/cofh_core/lang/zh_tw.json
> +  "commands.cofh.heal.success.single": "已治癒%s",
變數為玩家或數量時，請前後留空

2022-11-26 21:04 UTC, StarskyXIII commented on src/main/resources/assets/cofh_core/lang/zh_tw.json
> +  "info.cofh.energy_stored": "能量存儲",
存儲？儲存？

2022-11-26 21:04 UTC, StarskyXIII commented on src/main/resources/assets/cofh_core/lang/zh_tw.json
> +  "info.cofh.current_signal": "紅石信號：%s",
信號？訊號？

2022-11-26 21:04 UTC, StarskyXIII commented on src/main/resources/assets/cofh_core/lang/zh_tw.json
> +  "info.cofh.disabled": "禁用",
禁用？停用？

2022-11-26 21:04 UTC, StarskyXIII commented on src/main/resources/assets/cofh_core/lang/zh_tw.json
> +  "info.cofh.signal_required": "需要紅石信號",
信號？訊號？

2022-11-26 21:04 UTC, StarskyXIII commented on src/main/resources/assets/cofh_core/lang/zh_tw.json
> +  "enchantment.cofh_core.disabled.desc": "一個被禁用的附魔，沒有任何作用。",
禁用？停用？

2022-11-26 21:04 UTC, StarskyXIII commented on src/main/resources/assets/cofh_core/lang/zh_tw.json
> +  "enchantment.cofh_core.holding.desc": "提升特定物品的存儲容量。",
存儲？儲存？

2022-11-26 21:04 UTC, StarskyXIII commented on src/main/resources/assets/cofh_core/lang/zh_tw.json
> +  "info.cofh_core.fluid_filter.0": "將含有流體的容器放入槽位中以將其添加至過濾列表。",
食品添加物？

2022-11-26 21:04 UTC, StarskyXIII commented on src/main/resources/assets/cofh_core/lang/zh_tw.json
> +  "enchantment.minecraft.smite.desc": "提升對亡靈生物的傷害。",
你的附魔書上面寫亡靈剋星？

2022-11-26 21:04 UTC, StarskyXIII commented on src/main/resources/assets/cofh_core/lang/zh_tw.json
> +  "enchantment.minecraft.vanishing_curse.desc": "帶有該魔咒的物品會在使用者死亡後徹底消失。",
學會了，Minecraft 有魔咒系統

2022-11-26 21:04 UTC, StarskyXIII commented on src/main/resources/assets/cofh_core/lang/zh_tw.json
> +  "item.minecraft.lingering_potion.effect.amplification": "滯留型增幅藥水",
繁中藥水格式為 `飛濺 OO藥水`

2022-11-26 21:04 UTC, StarskyXIII commented on src/main/resources/assets/cofh_core/lang/zh_tw.json
> +  "item.minecraft.lingering_potion.effect.clarity": "滯留型洞察藥水",
繁中藥水格式為 `滯留 OO藥水`

2022-11-26 21:04 UTC, StarskyXIII commented on src/main/resources/assets/cofh_core/lang/zh_tw.json
> +  "enchantment.minecraft.silk_touch.desc": "被挖掘的方塊會精確地掉落其自身。",
你的附魔書上寫精準採集嗎

2022-11-26 21:04 UTC, StarskyXIII commented on src/main/resources/assets/cofh_core/lang/zh_tw.json
> +  "info.cofh.access": "訪問權限",
訪問？存取？

2022-11-26 21:04 UTC, StarskyXIII commented on src/main/resources/assets/cofh_core/lang/zh_tw.json
> +  "info.cofh.secure_notice": "注意：該服務器的管理員擁有無視安全設置訪問上鎖方塊/物品的權限。",
訪問？存取？

2022-11-26 21:04 UTC, StarskyXIII commented on src/main/resources/assets/cofh_core/lang/zh_tw.json
> +  "info.cofh.transfer_in_disabled": "自動輸入已禁用",
禁用？停用？

2022-11-27 05:34 UTC, Jimmy-sheep commented
以上的翻譯都修正了 

> 你的附魔書上面寫亡靈剋星？

說真的 我只是因為看不習慣簡體中文而來翻譯的 這模組也是因為跟朋友玩才接觸3 4天而已 我也不是專業的翻譯團隊 甚至連英文都不太好 有疑慮的部分可以提出來 你的語氣不需要那麼酸吧

2022-11-27 05:55 UTC, StarskyXIII commented
非常感謝你對繁中圈的貢獻，
我個人觀點是你今天想要簡轉繁翻譯，那就做到最基本的用語在地化再 PR 回官方，
未來該翻譯被合併後，會被所有繁體中文語言玩家使用，
我不希望因為用語在地化未完全，導致這些玩家逐漸潛移默化，習慣使用非台灣本土用語 :)
語氣很酸是我的錯，在這邊跟你致歉。

2022-11-27 06:09 UTC, Jimmy-sheep commented
> 非常感謝你對繁中圈的貢獻，我個人觀點是你今天想要簡轉繁翻譯，那就做到最基本的用語在地化再 PR 回官方，未來該翻譯被合併後，會被所有繁體中文語言玩家使用， 我不希望因為用語在地化未完全，導致這些玩家逐漸潛移默化，習慣使用非台灣本土用語 :) 

了解 有些詞彙其實我也有些困擾 畢竟網路上兩岸用語其實常常混淆 導致我自身也有些混亂 我也希望能夠完完全全使用台灣的用語來翻譯 但我也只能盡力減少 實在不能確定能夠十全十美

2022-11-28 20:07 UTC, StarskyXIII requested changes

2022-11-28 20:07 UTC, StarskyXIII commented on src/main/resources/assets/cofh_core/lang/zh_tw.json
> +  "info.cofh.claimable": "可聲明",
`可認領` 是否會比較好

2022-11-28 20:07 UTC, StarskyXIII commented on src/main/resources/assets/cofh_core/lang/zh_tw.json
> +  "info.cofh.click_to_claim": "§e§o點擊§r§7以獲取。",
這邊應該是指 `左鍵`，不曉得需不需要補上

2022-11-28 20:07 UTC, StarskyXIII commented on src/main/resources/assets/cofh_core/lang/zh_tw.json
> +  "info.cofh.key_not_bound": "按鍵綁定：CoFH-'%s'未設置。",
' ' 標點符號建議改成「」

2022-11-28 20:07 UTC, StarskyXIII commented on src/main/resources/assets/cofh_core/lang/zh_tw.json
> +  "info.cofh.mode_change": "按'%s'或'%s'變更模式。",
' ' 標點符號建議改成「」

2022-11-28 20:07 UTC, StarskyXIII commented on src/main/resources/assets/cofh_core/lang/zh_tw.json
> +  "info.cofh.hold_shift_for_details": "按住§e§oShift§r§7查看詳情",
英文前後 建議與中文字留空

2022-11-28 20:07 UTC, StarskyXIII commented on src/main/resources/assets/cofh_core/lang/zh_tw.json
> +  "info.cofh.use_sneak_activate": "潛行並使用以啟用。",
兩個用感覺有點繞口，看要不要改成像這樣 `潛行 + 右鍵以啟用。`

2022-11-28 20:07 UTC, StarskyXIII commented on src/main/resources/assets/cofh_core/lang/zh_tw.json
> +  "info.cofh_use_sneak_deactivate": "潛行並使用以關閉。",
同上，`潛行 + 右鍵以停用。`

2022-11-28 20:07 UTC, StarskyXIII commented on src/main/resources/assets/cofh_core/lang/zh_tw.json
> +  "info.cofh.filter.checkNBT.0": "忽略NBT",
英文與中文字間建議留空

2022-11-28 20:07 UTC, StarskyXIII commented on src/main/resources/assets/cofh_core/lang/zh_tw.json
> +  "info.cofh.configuration": "配置",
萬年翻譯難題，在此處最沒爭議的翻法應該是 `機器 I/O`

2022-11-28 20:07 UTC, StarskyXIII commented on src/main/resources/assets/cofh_core/lang/zh_tw.json
> +  "info.cofh.information": "訊息",
資訊，`Message` 才是 `訊息`

2022-11-28 20:07 UTC, StarskyXIII commented on src/main/resources/assets/cofh_core/lang/zh_tw.json
> +  "info.cofh.secure_notice": "注意：該服務器的管理員擁有無視安全設置存取上鎖方塊/物品的權限。",
伺服器

2022-11-28 20:07 UTC, StarskyXIII commented on src/main/resources/assets/cofh_core/lang/zh_tw.json
> +  "block.cofh_core.glossed_magma": "潛匿岩漿",
這邊我個人喜好會想超譯成 `暫態`，因為玩家遠離後只會存在短暫時間

2022-11-28 20:07 UTC, StarskyXIII commented on src/main/resources/assets/cofh_core/lang/zh_tw.json
> +  "effect.cofh_core.enderference": "影抑",
由於對岸 Ender 叫末影，所以這翻譯應該不適用於繁體中文，終界抑制

2022-11-28 20:07 UTC, StarskyXIII commented on src/main/resources/assets/cofh_core/lang/zh_tw.json
> +  "info.cofh_core.fluid_filter.0": "將含有流體的容器放入槽位中以將其新增至篩選列表。",
欄位

2022-11-28 20:07 UTC, StarskyXIII commented on src/main/resources/assets/cofh_core/lang/zh_tw.json
> +  "key.cofh.mode_change_increment": "循環至下一個模式",
`輪換` 會不會比較好

2022-11-28 20:07 UTC, StarskyXIII commented on src/main/resources/assets/cofh_core/lang/zh_tw.json
> +  "enchantment.minecraft.vanishing_curse.desc": "帶有該附魔的物品會在使用者死亡後徹底消失。",
澈底

2022-11-28 20:07 UTC, StarskyXIII commented on src/main/resources/assets/cofh_core/lang/zh_tw.json
> +  "item.minecraft.splash_potion.effect.enderference": "飛濺 抑影藥水",
由於對岸 Ender 叫末影，所以這翻譯應該不適用於繁體中文，終界抑制

2022-11-28 20:07 UTC, StarskyXIII commented on src/main/resources/assets/cofh_core/lang/zh_tw.json
> +  "item.minecraft.lingering_potion.effect.enderference": "滯留 抑影藥水",
由於對岸 Ender 叫末影，所以這翻譯應該不適用於繁體中文，終界抑制

2022-11-29 10:58 UTC, Jimmy-sheep commented on src/main/resources/assets/cofh_core/lang/zh_tw.json
> +  "info.cofh.claimable": "可聲明",
"info.cofh.claimable": "可認領",
"info.cofh.click_to_claim": "§e§o點擊§r§7以獲取。",

我實在不確定這個用在哪個地方 因此無法得知這個下一行`獲取`是否也需要翻譯為認領...
我先保持為`獲取`

2022-11-29 11:01 UTC, Jimmy-sheep commented on src/main/resources/assets/cofh_core/lang/zh_tw.json
> +  "info.cofh.click_to_claim": "§e§o點擊§r§7以獲取。",
原文其實沒寫很清楚是左鍵還是右鍵...我擔心也可能是點擊UI裡的按鈕...

2022-11-29 11:05 UTC, Jimmy-sheep commented on src/main/resources/assets/cofh_core/lang/zh_tw.json
> +  "info.cofh.mode_change": "按'%s'或'%s'變更模式。",
還是這邊引號改用雙引號 " " ? 因為中間通常是放鍵盤按鍵 也就是 "v"或"b" 
![image](https://user-images.githubusercontent.com/65125836/204512960-1110200c-1103-49f4-a4ec-5615591a9526.png)

2022-11-29 11:16 UTC, Jimmy-sheep commented on src/main/resources/assets/cofh_core/lang/zh_tw.json
> +  "info.cofh.secure_notice": "注意：該服務器的管理員擁有無視安全設置存取上鎖方塊/物品的權限。",
`Notice: Server Ops are able to freely access 'secure' blocks on this server.`
這邊我修改為`注意：伺服器管理員擁有無視「安全設置」，存取上鎖方塊/物品的權限。` 這樣念起來應該比較好換氣..?

2022-11-29 15:20 UTC, StarskyXIII commented on src/main/resources/assets/cofh_core/lang/zh_tw.json
> +  "info.cofh.claimable": "可聲明",
沒意外是信素安全鎖，將他跟物品合成後，可以把鎖安裝在熱力系列的物品上，像是包包。
首次安裝時，需要玩家先行使用一次，才知道這物品的主人是誰

2022-11-29 15:21 UTC, StarskyXIII commented on src/main/resources/assets/cofh_core/lang/zh_tw.json
> +  "info.cofh.mode_change": "按'%s'或'%s'變更模式。",
國文標點符號沒有 "" 這東東吧 XD

2022-11-29 17:26 UTC, Jimmy-sheep commented on src/main/resources/assets/cofh_core/lang/zh_tw.json
> +  "info.cofh.mode_change": "按'%s'或'%s'變更模式。",
呃 我把這部分視為英文 畢竟鍵盤按鍵名稱大多還是以英文為主...

2022-12-12 21:54 UTC, merged